roles:
  # https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/docker/documentation/
  - src: geerlingguy.docker

collections:
  - name: community.general
  - name: ansible.posix
  - name: community.docker
